disabled_rules :
- line_length
- multiple_closures_with_trailing_closure
- trailing_newline
- mark
- comment_spacing
- operator_usage_whitespace
- closure_spacing
- implicitly_unwrapped_optional
- colon
- identifier_name
- opening_brace
- force_cast
- type_name
- function_body_length
- cyclomatic_complexity
- trailing_whitespace
- omment_spacin
- identifier_name
- force_cast
- statement_position
- opening_brace
- empty_parentheses_with_trailing_closure

included :

identifier_name:
  allowed_symbols: "_"
 
 
opt_in_rules:
  - closure_spacing
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - legacy_multiple
  - legacy_random
  - operator_usage_whitespace
  - colon
  
excluded:
- Pods

