# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StockApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for StockApp
  pod 'Alamofire'
  pod 'SwiftLint'
  pod 'KakaoSDKCommon', '~> 2.11.1'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth', '~> 2.11.1'  # 사용자 인증
  pod 'KakaoSDKUser', '~> 2.11.1'  # 카카오 로그인, 사용자 관리
  #파이어베이스 
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  
  target 'StockAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'StockAppUITests' do
    # Pods for testing
  end
  
end
