# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StockApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StockApp
    pod 'Alamofire'
    pod 'SwiftLint'

  target 'StockAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StockAppUITests' do
    # Pods for testing
  end

end
